apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab-app
  template:
    metadata:
      labels:
        app: lab-app
    spec:
      containers:
        - name: lab-app
          image: docker.io/thecloudschool/lab-app:45248ebfec7a2d7ab1ee306c8ee40845a01a635f
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lab-app
spec:
  selector:
    app: lab-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
