apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-app
spec:
  project: default
  source:
    repoURL: https://github.com/BSK-CHN/Lab-Deploy.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
